Add CI step to GitHub Actions workflow
Introduce a new CI step that aggregates results from various dependencies, such as lib, cli, web-app, scripts, and platform-xtest. The step runs on Ubuntu 22.04 and aborts if any dependency fails.

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -275,3 +275,16 @@ jobs:
           echo "- [Command Line Tool](https://www.npmjs.com/package/@opentdf/ctl/v/${{ needs.deliver-ghp.outputs.FULL_VERSION }})">>$GITHUB_STEP_SUMMARY
       - run: >-
           echo "- [unpkg](https://unpkg.com/browse/@opentdf/sdk@${{ needs.deliver-ghp.outputs.FULL_VERSION }})">>$GITHUB_STEP_SUMMARY
+
+  ci:
+    needs:
+      - lib
+      - cli
+      - web-app
+      - scripts
+      - platform-xtest
+    runs-on: ubuntu-22.04
+    if: ${{ !cancelled() }}
+    steps:
+      - if: contains(needs.*.result, 'failure')
+        run: echo "Failed due to ${{ contains(needs.*.result, 'failure') }}" && exit 1
